# 86 labeled reference data
REFERENCE_DATA_SEED = [
    (["Fine Dining", "Romantic"], "I'm feeling like this should be a special moment and I want something memorable"),
    (["Cafe", "Casual Dining"], "I'm feeling relaxed and want a cozy place with a warm atmosphere"),
    (["Fast Food"], "I'm feeling a bit hungry and need something quick but still satisfying"),
    (["Comfort Food"], "I'm feeling nostalgic and want comfort food like home"),
    (["Casual Dining"], "I'm feeling like having a deep conversation in a quiet place"),
    (["Casual Dining"], "I'm feeling energetic and want a lively, fun atmosphere"),
    (["Fusion"], "I'm feeling curious and want to try something new and different"),
    (["Romantic", "Fine Dining"], "I'm feeling romantic and want a nice dinner setting"),
    (["Casual Dining"], "I'm feeling social and want a casual place to hang out with friends"),
    (["Comfort Food"], "I'm feeling indulgent and want something rich and satisfying"),
    (["Healthy"], "I'm feeling light and want something fresh and not heavy"),
    (["Cafe"], "I'm feeling like grabbing coffee and relaxing for a while"),
    (["Trendy"], "I'm feeling trendy and want a modern, stylish place"),
    (["Traditional"], "I'm feeling like something authentic and traditional"),
    (["Fine Dining"], "I'm feeling like something elegant but not too formal"),
    (["Fast Food"], "I'm feeling budget-conscious and just want something simple and filling"),
    (["Street Food"], "I'm feeling adventurous and want bold, spicy flavors"),
    (["Family Style"], "I'm feeling like a family-style meal with a welcoming vibe"),
    (["Cafe"], "I'm feeling drained and want a chill place to unwind"),
    (["Healthy"], "I'm feeling health-conscious and want something nutritious"),
    (["Fine Dining"], "I'm feeling like treating myself to something luxurious"),
    (["Brunch", "Casual Dining"], "I'm feeling like having a relaxed brunch"),
    (["Fast Food"], "I'm feeling rushed and need something fast"),
    (["Fine Dining"], "I'm feeling like taking my time and enjoying a long meal"),
    (["Fusion"], "I'm feeling experimental and want something unique"),
    (["Casual Dining"], "I'm feeling excited and want a buzzing, energetic place"),
    (["Cafe"], "I'm feeling like working or reading in a quiet café"),
    (["Steakhouse"], "I'm feeling like something smoky and grilled"),
    (["Casual Dining"], "I'm feeling cozy and want a rustic atmosphere"),
    (["Family Style"], "I'm feeling social and need a place for a group gathering"),
    (["Street Food"], "I'm feeling like street food with bold flavors"),
    (["Healthy"], "I'm feeling like something made with fresh local ingredients"),
    (["Fine Dining"], "I'm feeling like something high-end and beautifully presented"),
    (["Dessert"], "I'm feeling like something sweet and dessert-focused"),
    (["Comfort Food"], "I'm feeling homesick and want something like home cooking"),
    (["Casual Dining"], "I'm feeling cheerful and want a vibrant place"),
    (["Healthy"], "I'm feeling like something refreshing and light"),
    (["Fusion"], "I'm feeling curious and want to explore a new cuisine"),
    (["Casual Dining"], "I'm feeling very hungry and want a hearty meal"),
    (["Casual Dining"], "I'm feeling like something simple and satisfying"),
    (["Outdoor Dining", "Casual Dining"], "I'm feeling like sitting outdoors and enjoying fresh air"),
    (["Casual Dining"], "I'm feeling like a low-pressure, relaxed dining experience"),
    (["Seafood"], "I'm feeling like seafood and ocean-inspired flavors"),
    (["Trendy"], "I'm feeling like a modern, stylish dining experience"),
    (["Romantic"], "I'm feeling romantic and want a date night spot"),
    (["Fast Food"], "I'm feeling busy and need something quick and convenient"),
    (["Casual Dining"], "I'm feeling celebratory and want a place to enjoy with friends"),
    (["Fusion"], "I'm feeling like rich flavors and interesting textures"),
    (["Casual Dining"], "I'm feeling like discovering a hidden gem"),
    (["Casual Dining"], "I'm feeling calm and want a peaceful environment"),
    (["Fusion"], "I'm feeling adventurous and want fusion-style cuisine"),
    (["Family Style"], "I'm feeling hungry and want generous portions"),
    (["Comfort Food"], "I'm feeling nostalgic and want something familiar"),
    (["Fine Dining"], "I'm feeling like something upscale but still approachable"),
    (["Casual Dining"], "I'm feeling energetic and want a lively atmosphere"),
    (["Vegan"], "I'm feeling plant-based and want wholesome food"),
    (["Casual Dining"], "I'm feeling like a casual and easy lunch"),
    (["Comfort Food"], "I'm feeling like something warm and comforting"),
    (["Fusion"], "I'm feeling like a unique dining experience"),
    (["Casual Dining"], "I'm feeling relaxed and want to take my time eating"),
    (["Casual Dining"], "I'm feeling happy and want to celebrate with something nice"),
    (["Casual Dining"], "I'm feeling happy and just want to enjoy good food and a good vibe"),
    (["Cafe"], "I'm feeling calm and happy, just want a cozy place to relax"),
    (["Casual Dining"], "I'm feeling excited and happy, looking for a lively place"),
    (["Comfort Food"],"I'm feeling sad and want something comforting to cheer me up"),
    (["Comfort Food"], "I'm feeling a bit down and need something warm and familiar"),
    (["Cafe"], "I'm feeling tired and just want coffee and a quiet place to rest"),
    (["Cafe"], "I'm feeling exhausted and want somewhere peaceful to recharge"),
    (["Healthy"], "I'm feeling guilty and want something healthy and light"),
    (["Healthy"], "I'm feeling like I need to reset with something clean and nutritious"),
    (["Fast Food"], "I'm feeling super hungry and just want something quick and easy"),
    (["Fast Food"], "I'm feeling impatient and need food fast without waiting"),
    (["Romantic"], "I'm feeling in love and want a romantic dinner"),
    (["Romantic", "Fine Dining"], "I'm feeling romantic and want a beautiful, special dinner experience"),
    (["Fine Dining"], "I'm feeling proud and want to celebrate with something luxurious"),
    (["Fine Dining"], "I'm feeling accomplished and want to treat myself"),
    (["Street Food"], "I'm feeling adventurous and want to try bold street flavors"),
    (["Street Food"], "I'm feeling curious and want something exciting and different"),
    (["Brunch"], "I'm feeling relaxed and happy and want a slow brunch"),
    (["Brunch"], "I'm feeling like taking it easy with a nice weekend brunch"),
    (["Fusion"], "I'm feeling curious and want something creative and unexpected"),
    (["Fusion"], "I'm feeling adventurous and want to explore new flavor combinations"),
    (["Casual Dining"], "I'm feeling neutral and just want something simple and decent"),
    (["Casual Dining"], "I'm feeling okay and just want a straightforward meal"),
    (["Comfort Food"], "I'm feeling nostalgic and want something that reminds me of home"),
    (["Comfort Food"], "I'm feeling nostalgic and want something that reminds me of home"),
    (["Comfort Food"], "I'm feeling a bit emotional and want something comforting and familiar"),
    (["Cafe"], "I'm feeling relaxed and want a cozy place to sip coffee and unwind"),
    (["Cafe"], "I want a quiet cafe to read, relax, and enjoy a slow drink"),
    (["Cafe"], "Feeling like a leisurely coffee in a warm, cozy café where I can recharge"),
]